_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 24
                - 55
            "4": 3.13.2
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": darwin-arm64
