_wandb:
    value:
        cli_version: 0.19.5
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "3":
                - 1
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.4
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
