_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.12.4
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": darwin-arm64
        visualize:
            data_plot 0:
                panel_config:
                    fieldSettings:
                        x: b-values
                        "y": signal
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot 0_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot 1:
                panel_config:
                    fieldSettings:
                        x: b-values
                        "y": signal
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot 1_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot 2:
                panel_config:
                    fieldSettings:
                        x: b-values
                        "y": signal
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot 2_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot 3:
                panel_config:
                    fieldSettings:
                        x: b-values
                        "y": signal
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: ""
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot 3_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
