_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
