_wandb:
    value:
        cli_version: 0.19.5
        m:
            - "1": test_example.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_example.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_example._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_recall
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_recall
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_example.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_example.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_example._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_example.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_precision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_precision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.4.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.0.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.0.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_example.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_example.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.2.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv3.1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip3.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.0.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_example.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv4.0.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_example.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv1.1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.conv2.1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip2.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_example.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.classifier.6.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/model.skip1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "3":
                - 1
                - 7
                - 13
                - 23
                - 55
                - 62
                - 66
            "4": 3.12.4
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
