_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": darwin-arm64
        visualize:
            data_plot_D_epoch 0:
                panel_config:
                    fieldSettings:
                        x: D_ref
                        "y": D_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'D: epoch 0'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_D_epoch 0_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_D_epoch 10:
                panel_config:
                    fieldSettings:
                        x: D_ref
                        "y": D_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'D: epoch 10'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_D_epoch 10_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_D_epoch 20:
                panel_config:
                    fieldSettings:
                        x: D_ref
                        "y": D_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'D: epoch 20'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_D_epoch 20_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_D_epoch 30:
                panel_config:
                    fieldSettings:
                        x: D_ref
                        "y": D_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'D: epoch 30'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_D_epoch 30_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_D_epoch 40:
                panel_config:
                    fieldSettings:
                        x: D_ref
                        "y": D_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'D: epoch 40'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_D_epoch 40_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_Dp_epoch 0:
                panel_config:
                    fieldSettings:
                        x: Dp_ref
                        "y": Dp_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'Dp: epoch 0'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_Dp_epoch 0_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_Dp_epoch 10:
                panel_config:
                    fieldSettings:
                        x: Dp_ref
                        "y": Dp_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'Dp: epoch 10'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_Dp_epoch 10_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_Dp_epoch 20:
                panel_config:
                    fieldSettings:
                        x: Dp_ref
                        "y": Dp_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'Dp: epoch 20'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_Dp_epoch 20_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_Dp_epoch 30:
                panel_config:
                    fieldSettings:
                        x: Dp_ref
                        "y": Dp_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'Dp: epoch 30'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_Dp_epoch 30_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_Dp_epoch 40:
                panel_config:
                    fieldSettings:
                        x: Dp_ref
                        "y": Dp_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'Dp: epoch 40'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_Dp_epoch 40_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_f_epoch 0:
                panel_config:
                    fieldSettings:
                        x: f_ref
                        "y": f_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'f: epoch 0'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_f_epoch 0_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_f_epoch 10:
                panel_config:
                    fieldSettings:
                        x: f_ref
                        "y": f_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'f: epoch 10'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_f_epoch 10_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_f_epoch 20:
                panel_config:
                    fieldSettings:
                        x: f_ref
                        "y": f_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'f: epoch 20'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_f_epoch 20_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_f_epoch 30:
                panel_config:
                    fieldSettings:
                        x: f_ref
                        "y": f_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'f: epoch 30'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_f_epoch 30_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            data_plot_f_epoch 40:
                panel_config:
                    fieldSettings:
                        x: f_ref
                        "y": f_pred
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: 'f: epoch 40'
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: data_plot_f_epoch 40_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
